export const PALLETS = [
   {
      id: 0,
      contractorId: 0,
      jobId: 0,
      palletNumber: 1,
      palletLocation: 'A5',
   },
   {
      id: 1,
      contractorId: 0,
      jobId: 0,
      palletNumber: 2,
      palletLocation: 'C7',
   },
   {
      id: 2,
      contractorId: 0,
      jobId: 0,
      palletNumber: 3,
      palletLocation: 'L8',
   },
   {
      id: 3,
      contractorId: 0,
      jobId: 0,
      palletNumber: 4,
      palletLocation: 'L8',
   },
   {
      id: 4,
      contractorId: 0,
      jobId: 0,
      palletNumber: 5,
      palletLocation: 'L7',
   },
   {
      id: 5,
      contractorId: 0,
      jobId: 0,
      palletNumber: 6,
      palletLocation: 'J1',
   },
   {
      id: 6,
      contractorId: 0,
      jobId: 0,
      palletNumber: 7,
      palletLocation: 'K4',
   },
   {
      id: 7,
      contractorId: 0,
      jobId: 1,
      palletNumber: 1,
      palletLocation: 'C5',
   },
   {
      id: 8,
      contractorId: 0,
      jobId: 1,
      palletNumber: 2,
      palletLocation: 'D3',
   },
   {
      id: 9,
      contractorId: 0,
      jobId: 1,
      palletNumber: 3,
      palletLocation: 'Next Door',
   },
   {
      id: 10,
      contractorId: 0,
      jobId: 2,
      palletNumber: 1,
      palletLocation: 'Next Door',
   },
   {
      id: 11,
      contractorId: 1,
      jobId: 3,
      palletNumber: 1,
      palletLocation: 'A2',
   },
   {
      id: 12,
      contractorId: 1,
      jobId: 3,
      palletNumber: 2,
      palletLocation: 'H2',
   },
   {
      id: 13,
      contractorId: 1,
      jobId: 3,
      palletNumber: 3,
      palletLocation: 'C6',
   },
   {
      id: 14,
      contractorId: 1,
      jobId: 3,
      palletNumber: 4,
      palletLocation: 'A5',
   },
   {
      id: 15,
      contractorId: 3,
      jobId: 7,
      palletNumber: 1,
      palletLocation: 'I5',
   },
];
